- name: Install apt-transport-https (Debian)
  ansible.builtin.apt:
    name: apt-transport-https
    state: latest
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Download Brave GPG key (Debian)
  ansible.builtin.get_url:
    url: "https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg"
    dest: "/usr/share/keyrings/brave-browser-archive-keyring.gpg"
    mode: "0644"
    force: true
  when: ansible_os_family == 'Debian'

- name: Add Brave repository (Debian)
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
    state: present
    filename: brave-browser
  when: ansible_os_family == 'Debian'

- name: Install brave-browser (Debian)
  ansible.builtin.apt:
    name: "brave-browser"
    state: latest
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Add Brave repository (Fedora)
  ansible.builtin.yum_repository:
    name: brave-browser
    description: Brave Browser
    baseurl: https://brave-browser-rpm-release.s3.brave.com/x86_64/
    gpgkey: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    enabled: yes
    gpgcheck: yes
  when: ansible_os_family == 'RedHat'

- name: Install brave-browser (Fedora)
  ansible.builtin.dnf:
    name: brave-browser
    state: latest
    update_cache: true
  when: ansible_os_family == 'RedHat'
