- name: Install apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    state: latest
    update_cache: true

- name: Add Vivaldi repository with key
  ansible.builtin.deb822_repository:
    name: vivaldi-browser
    types: [deb]
    uris: "https://repo.vivaldi.com/stable/deb/"
    suites: stable
    components: [main]
    architectures: amd64
    signed_by: "https://repo.vivaldi.com/stable/linux_signing_key.pub"
    state: present
    enabled: true

- name: Install Vivaldi browser
  ansible.builtin.apt:
    name: vivaldi-stable
    state: latest
    update_cache: true
